##
#  ooooo      ooo            .oooooo..o oooo         o8o                .oooooo.   oooo
#  `888b.     `8'           d8P'    `Y8 `888         `"'               d8P'  `Y8b  `888
#   8 `88b.    8   .ooooo.  Y88bo.       888  oooo  oooo  ooo. .oo.   888           888 .oo.    .oooo.   ooo. .oo.    .oooooooo  .ooooo.
#   8   `88b.  8  d88' `88b  `"Y8888o.   888 .8P'   `888  `888P"Y88b  888           888P"Y88b  `P  )88b  `888P"Y88b  888' `88b  d88' `88b
#   8     `88b.8  888   888      `"Y88b  888888.     888   888   888  888           888   888   .oP"888   888   888  888   888  888ooo888
#   8       `888  888   888 oo     .d8P  888 `88b.   888   888   888  `88b    ooo   888   888  d8(  888   888   888  `88bod8P'  888    .o
#  o8o        `8  `Y8bod8P' 8""88888P'  o888o o888o o888o o888o o888o  `Y8bood8P'  o888o o888o `Y888""8o o888o o888o `8oooooo.  `Y8bod8P'
#                                                                                                                    d"     YD
#                                                                                                                    "Y88888P'
##
name: NoSkinChange
main: Kronnosy\NoSkinChange\NoSkinChange

api: 5.0.0
version: 1.0.0

author: "Kronnosy"
website: "https://github.com/Kronnosy"
description: "NoSkinChange prevents players from changing their skins within the server, ensuring that characters remain consistent and easily recognizable."

permissions:
  nsc.permission.use:
    default: op
    description: "Allows players to change skins (default for ops)."
